from __future__ import annotations

import json
from pathlib import Path

from ..models import CandidatePlan, ProjectConfig, SpacecraftConfig


TRAJECTORY_COLUMNS = [
    "Sat.ElapsedSecs",
    "Sat.EarthMJ2000Eq.X",
    "Sat.EarthMJ2000Eq.Y",
    "Sat.EarthMJ2000Eq.Z",
    "Sat.EarthMJ2000Eq.VX",
    "Sat.EarthMJ2000Eq.VY",
    "Sat.EarthMJ2000Eq.VZ",
    "Sat2.EarthMJ2000Eq.X",
    "Sat2.EarthMJ2000Eq.Y",
    "Sat2.EarthMJ2000Eq.Z",
    "Sat2.EarthMJ2000Eq.VX",
    "Sat2.EarthMJ2000Eq.VY",
    "Sat2.EarthMJ2000Eq.VZ",
]


def _gmat_path(path: Path) -> str:
    return path.resolve().as_posix().replace("'", "''")


def _spacecraft_block(
    gmat_name: str,
    spacecraft: SpacecraftConfig,
    epoch_utc: str,
    color: str,
) -> str:
    common = f"""Create Spacecraft {gmat_name};
{gmat_name}.DateFormat = UTCGregorian;
{gmat_name}.Epoch = '{epoch_utc}';
{gmat_name}.CoordinateSystem = EarthMJ2000Eq;
"""
    if spacecraft.keplerian is not None:
        elements = spacecraft.keplerian
        state = f"""{gmat_name}.DisplayStateType = Keplerian;
{gmat_name}.SMA = {elements.sma_km:.16g};
{gmat_name}.ECC = {elements.ecc:.16g};
{gmat_name}.INC = {elements.inc_deg:.16g};
{gmat_name}.RAAN = {elements.raan_deg:.16g};
{gmat_name}.AOP = {elements.aop_deg:.16g};
{gmat_name}.TA = {elements.ta_deg:.16g};
"""
    else:
        assert spacecraft.cartesian is not None
        r = spacecraft.cartesian.position_km
        v = spacecraft.cartesian.velocity_km_s
        state = f"""{gmat_name}.DisplayStateType = Cartesian;
{gmat_name}.X = {r[0]:.16g};
{gmat_name}.Y = {r[1]:.16g};
{gmat_name}.Z = {r[2]:.16g};
{gmat_name}.VX = {v[0]:.16g};
{gmat_name}.VY = {v[1]:.16g};
{gmat_name}.VZ = {v[2]:.16g};
"""
    physical = f"""{gmat_name}.DryMass = {spacecraft.dry_mass_kg:.16g};
{gmat_name}.Cd = 2.2;
{gmat_name}.Cr = 1.8;
{gmat_name}.DragArea = 15;
{gmat_name}.SRPArea = 1;
{gmat_name}.OrbitColor = {color};
"""
    return common + state + physical


def _burn_block(index: int, values: tuple[float, float, float]) -> str:
    name = f"Burn{index}"
    return f"""Create ImpulsiveBurn {name};
{name}.CoordinateSystem = Local;
{name}.Origin = Earth;
{name}.Axes = VNB;
{name}.Element1 = {values[0]:.16g};
{name}.Element2 = {values[1]:.16g};
{name}.Element3 = {values[2]:.16g};
{name}.DecrementMass = false;
{name}.Isp = 300;
{name}.GravitationalAccel = 9.81;
"""


def generate_gmat_bundle(
    config: ProjectConfig,
    plan: CandidatePlan,
    run_directory: str | Path,
) -> dict[str, Path]:
    run_dir = Path(run_directory).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)
    script_path = run_dir / "verify.script"
    trajectory_path = run_dir / "TrajectoryReport.csv"
    summary_path = run_dir / "FinalSummary.csv"
    manifest_path = run_dir / "candidate.json"
    log_path = run_dir / "GmatLog.txt"

    verification_horizon = min(
        config.scenario.tmax_s(),
        plan.evaluation_horizon_s + config.gmat.post_entry_buffer_s,
    )
    resources = [
        "% General Mission Analysis Tool (GMAT) script",
        "% Generated by TASA Orbit V4; trajectory and summary use separate files.",
        _spacecraft_block(
            "Sat", config.scenario.chaser, config.scenario.epoch_utc, "Red"
        ),
        _spacecraft_block(
            "Sat2", config.scenario.target, config.scenario.epoch_utc, "Green"
        ),
        """Create ForceModel TwoBodyFM;
TwoBodyFM.CentralBody = Earth;
TwoBodyFM.PrimaryBodies = {Earth};
TwoBodyFM.Drag = None;
TwoBodyFM.SRP = Off;
TwoBodyFM.RelativisticCorrection = Off;
TwoBodyFM.ErrorControl = RSSStep;
TwoBodyFM.GravityField.Earth.Degree = 0;
TwoBodyFM.GravityField.Earth.Order = 0;
TwoBodyFM.GravityField.Earth.PotentialFile = 'JGM2.cof';
TwoBodyFM.GravityField.Earth.TideModel = 'None';

Create Propagator Prop;
Prop.FM = TwoBodyFM;
Prop.Type = RungeKutta89;
"""
        + f"""Prop.InitialStepSize = {config.gmat.initial_step_s:.16g};
Prop.Accuracy = {config.gmat.accuracy:.16g};
Prop.MinStep = {config.gmat.min_step_s:.16g};
Prop.MaxStep = {config.gmat.max_step_s:.16g};
Prop.MaxStepAttempts = 100;
Prop.StopIfAccuracyIsViolated = true;
""",
    ]
    resources.extend(
        _burn_block(index, burn.dv_vnb_km_s)
        for index, burn in enumerate(plan.burns, start=1)
    )
    columns = ", ".join(TRAJECTORY_COLUMNS)
    resources.append(
        f"""Create ReportFile TrajectoryReport;
TrajectoryReport.Filename = '{_gmat_path(trajectory_path)}';
TrajectoryReport.Precision = 16;
TrajectoryReport.Add = {{{columns}}};
TrajectoryReport.WriteHeaders = true;
TrajectoryReport.FixedWidth = Off;
TrajectoryReport.Delimiter = Comma;
TrajectoryReport.WriteReport = true;
TrajectoryReport.AppendToExistingFile = false;

Create ReportFile FinalSummary;
FinalSummary.Filename = '{_gmat_path(summary_path)}';
FinalSummary.Precision = 16;
FinalSummary.WriteHeaders = true;
FinalSummary.FixedWidth = Off;
FinalSummary.Delimiter = Comma;
FinalSummary.WriteReport = false;
FinalSummary.AppendToExistingFile = false;
"""
    )

    mission: list[str] = ["BeginMissionSequence;"]
    current_time = 0.0
    for index, burn in enumerate(plan.burns, start=1):
        duration = burn.time_s - current_time
        if duration > 1e-10:
            mission.append(
                f"Propagate Prop(Sat, Sat2) {{Sat.ElapsedSecs = {duration:.16g}}};"
            )
        mission.append(f"Maneuver Burn{index}(Sat);")
        current_time = burn.time_s
    final_duration = verification_horizon - current_time
    if final_duration > 1e-10:
        mission.append(
            f"Propagate Prop(Sat, Sat2) {{Sat.ElapsedSecs = {final_duration:.16g}}};"
        )
    summary_fields = ["Sat.ElapsedSecs"]
    for index in range(1, len(plan.burns) + 1):
        summary_fields.extend(
            [f"Burn{index}.Element1", f"Burn{index}.Element2", f"Burn{index}.Element3"]
        )
    summary_fields.extend(TRAJECTORY_COLUMNS[1:])
    mission.append("Report FinalSummary " + " ".join(summary_fields) + ";")

    script_text = "\n\n".join(resources) + "\n\n" + "\n".join(mission) + "\n"
    script_path.write_text(script_text, encoding="utf-8")
    manifest = {
        "candidate": plan.model_dump(mode="json"),
        "verification_horizon_s": verification_horizon,
        "trajectory_columns": TRAJECTORY_COLUMNS,
        "mu_km3_s2": config.scenario.mu_km3_s2,
        "gmat_expected_mu_km3_s2": 398600.4415,
        "outputs": {
            "trajectory": trajectory_path.name,
            "summary": summary_path.name,
            "log": log_path.name,
        },
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return {
        "run_directory": run_dir,
        "script": script_path,
        "trajectory": trajectory_path,
        "summary": summary_path,
        "manifest": manifest_path,
        "log": log_path,
    }
